In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.3.0


In [3]:
a = tf.constant("Hello ")
b = tf.constant("World!!")

In [4]:
c = a + b

In [5]:
with tf.Session() as sess:
    
    print(sess.run(c))

b'Hello World!!'


In [6]:
X = tf.constant([[1,2,3],[4,5,6]])
y = tf.constant([[1,2,3],[4,5,6]])

In [7]:
Z = X + y

In [8]:
ses = tf.InteractiveSession()

In [9]:
print(ses.run(Z))

[[ 2  4  6]
 [ 8 10 12]]


In [10]:
print(Z.eval())

[[ 2  4  6]
 [ 8 10 12]]


In [11]:
Fill = tf.fill((4,4),10)
Ones = tf.ones((4,4))
Zeros = tf.zeros((4,4))
normal = tf.random_normal((4,4))
uniform = tf.random_uniform((4,4))

In [12]:
ops_list = [Fill,Ones,Zeros,normal,uniform]
for op in ops_list:
    
    print(op.eval())

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[-1.08993423  0.64072639 -2.71995854 -1.59530544]
 [-0.87531143 -0.96731108 -0.99165428 -1.07875478]
 [ 0.24141359  0.07892641 -1.71277797 -0.70348227]
 [-0.85867727  0.30798855  0.68535483  0.76570505]]
[[ 0.67555785  0.18766427  0.09942043  0.13249779]
 [ 0.25793517  0.03256309  0.1772064   0.76487935]
 [ 0.52362359  0.95540738  0.53970027  0.86697149]
 [ 0.26151574  0.67856562  0.25328434  0.36177456]]


In [13]:
Graph1 = tf.get_default_graph()
Graph2 = tf.Graph()
print(Graph2)

In [14]:
with Graph2.as_default():
    
    print (Graph2 is tf.get_default_graph())

True


In [15]:
const = tf.constant([[4,4],[5,5]])

In [16]:
var1 = tf.Variable(initial_value=const)

In [17]:
place = tf.placeholder(dtype=tf.float32,shape=(None,2))

In [18]:
init = tf.global_variables_initializer()

In [19]:
with tf.Session() as ses:
    
    ses.run(init)
    print(ses.run(var1))

[[4 4]
 [5 5]]


In [20]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)


In [21]:
import numpy as np

In [22]:
np.random.seed(100)

In [25]:
rand1 = np.random.random((5,5))
rand1 

array([[ 0.25242635,  0.79566251,  0.01525497,  0.59884338,  0.60380454],
       [ 0.10514769,  0.38194344,  0.03647606,  0.89041156,  0.98092086],
       [ 0.05994199,  0.89054594,  0.5769015 ,  0.74247969,  0.63018394],
       [ 0.58184219,  0.02043913,  0.21002658,  0.54468488,  0.76911517],
       [ 0.25069523,  0.28589569,  0.85239509,  0.97500649,  0.88485329]])

In [26]:
rand2 = np.random.random((5,1))
rand2 

array([[ 0.35950784],
       [ 0.59885895],
       [ 0.35479561],
       [ 0.34019022],
       [ 0.17808099]])

In [27]:

with tf.Session() as sess:
    
    add_result = sess.run(tf.add(a,b),feed_dict={a:rand1,b:rand2})
    print(add_result)

[[ 0.61193419  1.15517044  0.37476283  0.95835125  0.96331239]
 [ 0.70400661  0.98080242  0.63533503  1.48927045  1.57977986]
 [ 0.41473758  1.24534154  0.93169713  1.09727526  0.98497951]
 [ 0.92203236  0.36062932  0.55021679  0.88487506  1.10930538]
 [ 0.4287762   0.46397668  1.03047609  1.1530875   1.06293428]]
